# 100 numpy exercises



#### 1. Import the numpy package under the name `np` (???)

In [21]:
import numpy as np

#### 2. Print the numpy version and the configuration (???)

In [22]:
print(np.__version__)
print(np.show_config)

1.18.5
<function show at 0x0000020A78AA08B0>


#### 3. Create a null vector of size 10 (???)

In [23]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (???)

In [24]:
a = np.array([1, 2])
print(a.size*a.itemsize)

8


#### 5. How to get the documentation of the numpy add function from the command line? (???)

In [25]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (???)

In [26]:
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (???)

In [27]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (???)

In [28]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (???)

In [29]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (???)

In [30]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (???)

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (???)

In [32]:
np.random.random((3,3,3))

array([[[0.6917253 , 0.43425717, 0.6226793 ],
        [0.89725237, 0.23453348, 0.73632391],
        [0.23334608, 0.54134735, 0.47988204]],

       [[0.47093738, 0.85934496, 0.32995811],
        [0.75329873, 0.05505369, 0.38274875],
        [0.46357558, 0.1990875 , 0.53095164]],

       [[0.04162073, 0.05661598, 0.00754189],
        [0.84508543, 0.12255054, 0.88461526],
        [0.43778057, 0.67938669, 0.46440985]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (???)

In [34]:
a = np.random.random((10,10))
print(np.min(a),np.max(a))

0.012592810559576173 0.991096244217514


#### 14. Create a random vector of size 30 and find the mean value (???)

In [35]:
np.random.random(30).mean()

0.5300021408858705

#### 15. Create a 2d array with 1 on the border and 0 inside (???)

In [42]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (???)

In [46]:
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (???)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [47]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (???)

In [48]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (???)

In [57]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [58]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (???)

In [59]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (???)

In [60]:
a = np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
print(a)

[[ 1.11177608  0.75774466 -1.32744122  0.39953331 -0.84582864]
 [ 1.07025439 -0.03335812  1.28336295  0.61506915  1.12630766]
 [ 0.97038375 -1.15357441 -0.55326851 -0.92900873  0.09150767]
 [ 1.29251021 -0.33180858 -0.62425593 -1.70940067  1.09070013]
 [-1.61290363 -0.42947804  1.45666645 -0.83583964 -0.8796503 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (???)

In [63]:
a = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-63-4a4c627d38af>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (???)

In [65]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (???)

In [66]:
a = np.arange(11)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (???)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [71]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (???)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [82]:
print("1j*Z")

1j*Z


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [83]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-83-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-83-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (???)

In [84]:
np.where(a>0, np.ceil(a), np.floor(a))

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7.,  8.,  9., 10.])

#### 30. How to find common values between two arrays? (???)

In [92]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[1 2 6]


#### 31. How to ignore all numpy warnings (not recommended)? (???)

In [95]:
None

#### 32. Is the following expressions true? (???)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [94]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-94-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (???)

In [99]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2021-01-30
2021-01-31
2021-02-01


#### 34. How to get all the dates corresponding to the month of July 2016? (???)

In [100]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (???)

In [101]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (???)

In [102]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[5. 4. 7. 0. 1. 8. 7. 3. 5. 2.]
[5. 4. 7. 0. 1. 8. 7. 3. 5. 2.]
[5. 4. 7. 0. 1. 8. 7. 3. 5. 2.]
[5 4 7 0 1 8 7 3 5 2]
[5. 4. 7. 0. 1. 8. 7. 3. 5. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (???)

In [103]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (???)

In [104]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (???)

In [105]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (???)

In [109]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06828586 0.10660859 0.15933565 0.32088804 0.37283942 0.4021088
 0.42401573 0.73086386 0.91681459 0.91922321]


#### 41. How to sum a small array faster than np.sum? (???)

In [110]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (???)

In [111]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (???)

In [113]:
None

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (???)

In [117]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.63270586 0.83069244 0.93746751 0.95705363 0.5058014  0.81495066
 0.72577865 0.78451294 0.69502919 0.80257417]
[0.03654107 1.5160234  0.58341916 0.26902709 0.24834597 0.31717087
 1.14711389 1.15929357 0.60938576 1.03164357]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (???)

In [118]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.45177217 0.         0.19131814 0.97222989 0.19690991 0.47487646
 0.05187143 0.6775869  0.44895324 0.25855037]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (???)

In [119]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [120]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (???)

In [121]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (???)

In [122]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (???)

In [123]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

85


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (???)

In [124]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-124-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (???)

In [125]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.83574036 0.76921779 0.55581706 0.36777161 0.60927588
  0.78070512 1.1884478  0.96366768 0.71330047]
 [0.83574036 0.         0.39105595 0.38616767 0.76839878 0.86248832
  0.06301501 0.7637587  0.79146174 0.50056288]
 [0.76921779 0.39105595 0.         0.22180615 0.53524334 0.53232244
  0.34399412 0.46393334 0.40459234 0.12699967]
 [0.55581706 0.38616767 0.22180615 0.         0.38857468 0.48407889
  0.32348142 0.67787151 0.54900975 0.22089171]
 [0.36777161 0.76839878 0.53524334 0.38857468 0.         0.24454666
  0.70542571 0.87660213 0.61607717 0.43577884]
 [0.60927588 0.86248832 0.53232244 0.48407889 0.24454666 0.
  0.80147152 0.74177228 0.44122317 0.40675308]
 [0.78070512 0.06301501 0.34399412 0.32348142 0.70542571 0.80147152
  0.         0.74224042 0.74781727 0.44721051]
 [1.1884478  0.7637587  0.46393334 0.67787151 0.87660213 0.74177228
  0.74224042 0.         0.31522572 0.4777504 ]
 [0.96366768 0.79146174 0.40459234 0.54900975 0.61607717 0.44122317
  0.74781727 0.31522

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [126]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[ 0 54 30 19  9 13 20 98 49  4]


#### 54. How to read the following file? (???)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [127]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (???)

In [128]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (???)

In [129]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (???)

In [130]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (???)

In [131]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.25612054  0.22408246 -0.05431306 -0.21846373 -0.18665782  0.33371398
   0.39986657 -0.446151    0.18587729 -0.49407523]
 [ 0.28063691 -0.15585652 -0.33185794 -0.51707518  0.11742492  0.30315107
   0.35395027  0.07729341 -0.23826767  0.11060073]
 [ 0.19356638  0.20887254  0.08222117  0.2911826   0.21450999 -0.2071198
  -0.2218728  -0.15347866 -0.28261734 -0.12526409]
 [-0.37001543  0.14166302 -0.06690346  0.22301931 -0.25715988  0.07108671
   0.43519413 -0.36234559 -0.09602892  0.28149012]
 [-0.04984484 -0.48398481  0.46889383  0.21377889  0.46534985 -0.47234487
  -0.29175575  0.09166795  0.35067681 -0.29243705]]


#### 59. How to sort an array by the nth column? (???)

In [132]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 0 4]
 [5 9 4]
 [2 4 1]]
[[7 0 4]
 [2 4 1]
 [5 9 4]]


#### 60. How to tell if a given 2D array has null columns? (???)

In [133]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (???)

In [135]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.33266691749592736


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (???)

In [136]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (???)

In [137]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (???)

In [138]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 3. 5. 1. 2. 3. 3. 5. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (???)

In [139]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (???)

In [140]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (???)

In [141]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[54 50 75 56]
 [50 64 60 38]
 [52 28 49 68]]
[[54 50 75 56]
 [50 64 60 38]
 [52 28 49 68]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (???)

In [142]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.57794809 0.54437101 0.56752469 0.64208817 0.5435141  0.49192789
 0.5748291  0.44721468 0.3044052  0.65221174]


#### 69. How to get the diagonal of a dot product? (???)

In [143]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([1.59380327, 1.69083997, 1.86371607, 1.63294483, 1.81299861])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (???)

In [144]:

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (???)

In [145]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (???)

In [146]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (???)

In [147]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 21) ( 0, 58) ( 4, 10) ( 4, 47) (10, 47) (11, 13) (11, 69) (13, 69)
 (15, 32) (15, 85) (20, 25) (20, 37) (21, 58) (23, 64) (23, 72) (25, 37)
 (27, 91) (29, 36) (29, 48) (32, 85) (36, 48) (36, 58) (36, 79) (58, 79)
 (64, 72) (71, 84) (71, 96) (84, 96) (91, 91)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (???)

In [148]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (???)

In [149]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (???)

In [150]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (???)

In [151]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.60515123,  0.43549087,  0.52442456,  0.0356695 , -0.23883629,
       -0.84143239,  0.19764735, -0.18077792,  0.13691257,  0.68599021,
       -0.38823498,  0.38583286,  0.26095065,  0.73373092,  0.01910138,
        0.13498975, -0.52380018,  0.18579632, -0.59756718,  0.67430642,
       -0.36618711, -0.17388824,  0.47300426, -0.13042448, -0.69316436,
       -0.1209151 ,  0.96355909,  0.92080749, -0.68705478, -0.81773626,
       -0.81637611, -0.95952536,  0.94555061,  0.10849992,  0.37233389,
        0.91068372,  0.65122164, -0.1956454 , -0.80617708,  0.91380286,
       -0.6473517 ,  0.4823098 ,  0.86612919,  0.27201003, -0.64399615,
       -0.26976413,  0.63029974,  0.60577697, -0.08888142,  0.3809405 ,
       -0.99837241,  0.9020259 ,  0.6519518 , -0.49950213, -0.75413816,
       -0.93755663, -0.97512816,  0.91808147,  0.15909129, -0.26003462,
        0.71510419,  0.98702818,  0.43206768, -0.57933859,  0.97025575,
       -0.09054095, -0.53450864,  0.03220686,  0.7651035 , -0.20

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (???)

In [152]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.87747012  4.43402821  6.03081773  0.68229152  3.83914465 11.32381182
  6.02971498  3.8806894   2.60546498  8.60913116]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (???)

In [153]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.34715515  0.457134    3.4800939  12.12478968  8.20114654  5.00513812
   6.17297549  0.24367633  2.02273733  0.86902738]
 [ 8.18808109 11.62821581 16.09927037  0.36086368 16.21096296 13.10996272
  18.51066545  5.20847391  6.90630671  0.54245396]
 [ 3.95038303  2.62288699  4.90164439 11.66489844  4.31862226  1.1713101
   8.80271778  6.4339815   3.1167776   5.39329033]
 [ 0.40540562  5.61926124  0.54415218 15.38593657  9.28879852  6.03357322
   1.29474364  5.62564882  4.79605062  5.96468922]
 [ 8.36893468  0.22517888  1.55171643 15.42581351  0.06425435  3.21886961
   6.11226158  7.77164473  7.09647028  7.89696605]
 [ 3.42311662 10.92927884 11.91687465  5.59853441  4.35042708  1.2910363
  16.80708538 14.39684831  5.65892813 11.81718496]
 [ 3.52771882  2.13120704  6.81842428  8.48646892 12.01499082  8.83065809
   8.99763958  0.43754811  5.33005798  2.65755809]
 [ 9.09317963  3.16689605  9.40107244  5.13925125 17.65705088 14.46037892
  10.48543485  4.13209943 11.08922781  7.47443214]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (???)

In [154]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 4 8 6 0 8 6 9 7 0]
 [1 2 6 5 3 8 9 1 0 5]
 [8 2 8 4 9 8 4 8 0 6]
 [1 1 3 8 5 9 8 2 9 9]
 [5 8 4 5 9 1 9 1 9 1]
 [2 2 8 0 5 3 7 5 6 4]
 [5 6 5 3 2 4 7 3 8 8]
 [1 2 3 2 9 5 8 3 7 0]
 [3 7 4 2 3 7 4 6 7 3]
 [7 5 8 3 9 0 2 9 1 8]]
[[0 0 0 0 0]
 [0 0 4 8 6]
 [0 1 2 6 5]
 [0 8 2 8 4]
 [0 1 1 3 8]]


<ipython-input-154-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (???)

In [155]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (???)

In [156]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [157]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (???)

In [158]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 2]
   [0 1 4]
   [1 1 0]]

  [[0 2 0]
   [1 4 0]
   [1 0 3]]

  [[2 0 1]
   [4 0 3]
   [0 3 1]]

  [[0 1 4]
   [0 3 1]
   [3 1 0]]

  [[1 4 0]
   [3 1 3]
   [1 0 1]]

  [[4 0 3]
   [1 3 4]
   [0 1 2]]

  [[0 3 1]
   [3 4 1]
   [1 2 0]]

  [[3 1 3]
   [4 1 2]
   [2 0 0]]]


 [[[0 1 4]
   [1 1 0]
   [4 1 1]]

  [[1 4 0]
   [1 0 3]
   [1 1 1]]

  [[4 0 3]
   [0 3 1]
   [1 1 3]]

  [[0 3 1]
   [3 1 0]
   [1 3 4]]

  [[3 1 3]
   [1 0 1]
   [3 4 1]]

  [[1 3 4]
   [0 1 2]
   [4 1 2]]

  [[3 4 1]
   [1 2 0]
   [1 2 0]]

  [[4 1 2]
   [2 0 0]
   [2 0 1]]]


 [[[1 1 0]
   [4 1 1]
   [2 4 0]]

  [[1 0 3]
   [1 1 1]
   [4 0 1]]

  [[0 3 1]
   [1 1 3]
   [0 1 0]]

  [[3 1 0]
   [1 3 4]
   [1 0 4]]

  [[1 0 1]
   [3 4 1]
   [0 4 4]]

  [[0 1 2]
   [4 1 2]
   [4 4 3]]

  [[1 2 0]
   [1 2 0]
   [4 3 3]]

  [[2 0 0]
   [2 0 1]
   [3 3 4]]]


 [[[4 1 1]
   [2 4 0]
   [2 1 0]]

  [[1 1 1]
   [4 0 1]
   [1 0 0]]

  [[1 1 3]
   [0 1 0]
   [0 0 2]]

  [[1 3 4]
   [1 0 4]
   [0 2 4]]

  [[3 4 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (???)

In [159]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 13 15  5 11]
 [13  5 15  5 14]
 [15 15  1 42  3]
 [ 5  5 42  9 11]
 [11 14  3 11  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (???)

In [160]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (???)

In [161]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (???)

In [162]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1

#### 89. How to get the n largest values of an array (???)

In [163]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (???)

In [164]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (???)

In [165]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (???)

In [170]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.95 s ± 63.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
582 ms ± 38.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
325 ms ± 11.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (???)

In [169]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (???)

In [172]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 2]
 [0 1 3]
 [3 0 0]
 [2 2 1]
 [3 0 3]
 [4 2 0]
 [0 1 2]
 [0 3 2]
 [4 3 2]
 [0 4 0]]
[[0 1 2]
 [0 1 3]
 [3 0 0]
 [2 2 1]
 [3 0 3]
 [4 2 0]
 [0 1 2]
 [0 3 2]
 [4 3 2]
 [0 4 0]]
[[0 1 2]
 [0 1 3]
 [3 0 0]
 [2 2 1]
 [3 0 3]
 [4 2 0]
 [0 1 2]
 [0 3 2]
 [4 3 2]
 [0 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (???)

In [173]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (???)

In [174]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (???)

In [175]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.12640427, 0.07248879, 0.23831993, 0.37415378, 0.5571371 ,
        0.34444972, 0.19960691, 0.04497255, 0.29909482, 0.07049955],
       [0.07935799, 0.04550926, 0.14961988, 0.23489786, 0.34977681,
        0.21624933, 0.12531542, 0.02823426, 0.18777502, 0.04426039],
       [0.04712269, 0.02702335, 0.08884412, 0.13948209, 0.20769708,
        0.12840861, 0.07441216, 0.01676547, 0.1115006 , 0.02628177],
       [0.13905427, 0.07974316, 0.26216998, 0.4115975 , 0.61289301,
        0.37892078, 0.21958272, 0.04947321, 0.32902696, 0.07755484],
       [0.19964571, 0.11449041, 0.37640779, 0.59094679, 0.87995471,
        0.54403154, 0.31526359, 0.07103065, 0.472397  , 0.11134855],
       [0.20567997, 0.11795086, 0.38778466, 0.60880806, 0.90655121,
        0.56047481, 0.32479238, 0.07317754, 0.48667513, 0.11471404],
       [0.03219392, 0.01846218, 0.06069774, 0.09529328, 0.14189733,
        0.08772795, 0.05083791, 0.01145407, 0.0761765 , 0.01795554],
       [0.08865162, 0.05083886, 0.1671418

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (???)?

In [176]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (???)

In [177]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (???)

In [178]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.08212    0.3042375]
